In [61]:
import torch
import numpy as np
import random
torch.__version__

'2.0.1'

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([1,2,3,4])
vector

tensor([1, 2, 3, 4])

In [8]:
vector.ndim

1

In [11]:
vector.size()

torch.Size([4])

In [12]:
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.size()

torch.Size([2, 3])

In [15]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [16]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([2, 2, 3])

In [19]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.6714, 0.5105, 0.7707, 0.8925],
         [0.2722, 0.7651, 0.0162, 0.7073],
         [0.7441, 0.8753, 0.0090, 0.2563]]),
 torch.float32)

In [20]:
print(random_tensor)
print(f"Shape of tensor: {random_tensor.shape}")
print(f"Datatype of tensor: {random_tensor.dtype}")
print(f"Device tensor is stored on: {random_tensor.device}")

tensor([[0.6714, 0.5105, 0.7707, 0.8925],
        [0.2722, 0.7651, 0.0162, 0.7073],
        [0.7441, 0.8753, 0.0090, 0.2563]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [21]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [22]:
tensor * 10

tensor([10, 20, 30])

In [23]:
# Notice that the tensor didn't change
# Tensors will only change when they are re-assigned
tensor

tensor([1, 2, 3])

In [26]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [27]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [28]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [29]:
# It is more common to use `*` instead of `torch.multiply`
tensor * 10

tensor([10, 20, 30])

In [30]:
tensor * tensor

tensor([1, 4, 9])

In [31]:
# `*` means element-wise multiplication
# `@` means matrix multiplication
tensor @ tensor

tensor(14)

In [32]:
%%time
# Matrix multiplication of vectors by hand
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 662 µs, sys: 1.32 ms, total: 1.99 ms
Wall time: 1.65 ms


tensor(14)

In [36]:
%%time
# Matrix multiplication of vectors with torch
tensor @ tensor

CPU times: user 196 µs, sys: 63 µs, total: 259 µs
Wall time: 238 µs


tensor(14)

In [39]:
torch.manual_seed(42)

tensor_A = torch.tensor([[1, 2, 3],
                         [3, 4, 5],
                         [5, 6, 7]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
linear = torch.nn.Linear(in_features=3,
                         out_features=6)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape} \n")
print(f"Output : \n{output} \n\nOutput shape: {output.shape} \n")

Input shape: torch.Size([3, 3]) 

Output : 
tensor([[0.7245, 0.7740, 1.6579, 0.8366, 1.1836, 1.4476],
        [2.2952, 1.8148, 2.7918, 1.2092, 2.7499, 2.3454],
        [3.8659, 2.8555, 3.9257, 1.5819, 4.3161, 3.2432]],
       grad_fn=<AddmmBackward0>) 

Output shape: torch.Size([3, 6]) 



In [40]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # Must be float to calculate mean
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [44]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [45]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [46]:
# Change view points to the same data, but in a different view
# So if we change `z`, we will also change `x`
z = x.view(1,7)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [53]:
x_stacked = torch.stack([x, x, x, x, x, x, x], dim=1) # dim=0 means stack vertically, dim=1 means stack horizontally
x_stacked

tensor([[5., 5., 5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7., 7.]])

In [55]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove the extra dimentsion from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [59]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [60]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

# Permuting returns a view, any changes on the permuted tensor will affect the original tensor

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [62]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [63]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [64]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

Tensor B:
tensor([[0.1336, 0.9666, 0.9754, 0.8474],
        [0.8988, 0.1105, 0.4563, 0.9719],
        [0.3968, 0.1496, 0.4743, 0.9973]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [65]:
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# You have to reset the seed every time you want to generate a new random tensor
# Or else tensor C and tensor D are different
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [67]:
torch.cuda.is_available()

False