# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x

tensor([[0.1554, 0.4793, 0.6630, 0.5223, 0.4349, 0.7744, 0.2353],
        [0.0896, 0.3061, 0.5204, 0.4736, 0.4043, 0.1772, 0.9736],
        [0.9636, 0.3992, 0.7777, 0.2306, 0.8240, 0.5080, 0.9313],
        [0.0964, 0.3321, 0.8671, 0.4974, 0.0953, 0.4565, 0.8778],
        [0.3523, 0.7900, 0.5441, 0.2008, 0.1719, 0.5128, 0.6402],
        [0.9182, 0.4485, 0.6201, 0.9347, 0.0985, 0.5092, 0.5733],
        [0.7996, 0.7894, 0.7278, 0.2065, 0.0103, 0.7438, 0.7168]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
y = torch.rand(1, 7)

# Perform matrix multiplication 
result = torch.matmul(x, y.T)
result

tensor([[1.7402],
        [1.5704],
        [2.6191],
        [1.8426],
        [1.9446],
        [2.5794],
        [2.5748]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7, 7)
y = torch.rand(1, 7)

# Matrix multiply tensors
result = torch.matmul(x, y.T)
result, result.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.mps.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
torch.mps.manual_seed(1234)

# Check for access to GPU
torch.backends.mps.is_available()

# Create two random tensors on GPU
x = torch.rand(2, 3, device='mps')
y = torch.rand(2, 3, device='mps')
x, y


(tensor([[0.4794, 0.7608, 0.8283],
         [0.8029, 0.6423, 0.0597]], device='mps:0'),
 tensor([[0.0223, 0.9878, 0.2711],
         [0.9123, 0.7672, 0.8879]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
torch.matmul(x, y.T)

tensor([[0.9868, 1.7565],
        [0.6685, 1.2782]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [21]:
# Find max
print(torch.max(torch.matmul(x, y.T)))
# Find min
print(torch.min(torch.matmul(x, y.T)))


tensor(1.7565, device='mps:0')
tensor(0.6685, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [22]:
# Find arg max
print(torch.argmax(torch.matmul(x, y.T)))

# Find arg min
print(torch.argmin(torch.matmul(x, y.T)))

tensor(1, device='mps:0')
tensor(2, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [23]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x = torch.rand(1, 1, 1, 10)
print(x, x.shape)

# Remove single dimensions
x = x.squeeze()
print(x, x.shape)

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
